addinf files

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,7 +1,14 @@
 pipeline {
     agent any
 
+    environment {
+        IMAGE_NAME = "springboot-monitoring"
+        CONTAINER_NAME = "springboot-app"
+        APP_PORT = "8082"
+    }
+
     stages {
+
         stage('Checkout') {
             steps {
                 checkout scm
@@ -14,10 +21,52 @@ pipeline {
             }
         }
 
-        stage('Test') {
+        stage('Unit Test') {
             steps {
                 bat 'mvn test'
             }
+        }
+
+        stage('Build Docker Image') {
+            steps {
+                bat 'docker build -t %IMAGE_NAME% .'
+            }
+        }
+
+        stage('Stop Old Container') {
+            steps {
+                bat 'docker rm -f %CONTAINER_NAME% || exit 0'
+            }
+        }
+
+        stage('Run Docker Container') {
+            steps {
+                bat 'docker run -d --name %CONTAINER_NAME% -p %APP_PORT%:8082 %IMAGE_NAME%'
+            }
+        }
+
+        stage('Application Health Check') {
+            steps {
+                bat 'curl http://localhost:%APP_PORT%/actuator/health'
+            }
+        }
+
+        stage('Verify Prometheus Metrics') {
+            steps {
+                bat 'curl http://localhost:%APP_PORT%/actuator/prometheus'
+            }
+        }
+    }
+
+    post {
+        success {
+            echo 'Application deployed successfully.'
+            echo 'Prometheus metrics endpoint is available.'
+            echo 'Open Grafana to view dashboards.'
+        }
+
+        failure {
+            echo 'Pipeline failed.'
         }
     }
 }
